version: '3.8'

services:
  server:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api-server
    container_name: img-api
    volumes:
      - ./api/:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - NODE_ENV=production
      - API_PORT
      - CLOUD_NAME
      - CLOUD_API_KEY
      - CLOUD_SECRET
    networks:
      - img-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client-server
    container_name: img-client
    volumes:
      - ./client/:/usr/src/client
      - /usr/src/client/node_modules
    depends_on:
      - server
    ports:
      - ${REACT_PORT}:${REACT_PORT}
    environment:
      - REACT_PORT
      - AUTH0-DOMAIN
      - AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET
    networks:
      - img-network

networks:
  img-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
